// Shared nested translation dictionary (single source of truth).
// Consumed by src/lib/i18n.jsx, which flattens it into dotted keys.

export const nestedTranslations = {
  ka: {
    nav: {
      markets: "ბაზრები",
      whyNovax: "რატომ GNG",
      security: "უსაფრთხოება",
      portfolio: "პორტფელი",
      aiTrading: "AI ვაჭრობა",
      botPlans: "ბოტის პაკეტები",
      orders: "ორდერები",
      recurring: "ავტოშენაძენი",
      referrals: "მოწვევები",
      wallet: "საფულე",
    },
    common: {
      menu: "მენიუ",
      close: "დახურვა",
      login: "შესვლა",
      signUp: "რეგისტრაცია",
      signOut: "გასვლა",
      dashboard: "ჩემი კაბინეტი →",
      language: "ენა",
      portfolio: "პორტფელი",
      email: "ელფოსტა",
      password: "პაროლი",
      backHome: "← მთავარ გვერდზე",
      pleaseWait: "ერთი წუთით...",
    },
    landing: {
      heroEyebrow: "ვაჭრობა ზედმეტი ხმაურის გარეშე",
      heroTitle: "იმოძრავე ბაზრის რიტმში.|კონტროლი შენს ხელშია.",
      heroText:
        "გასაგები და მოწესრიგებული სივრცე ციფრული აქტივებისთვის — მათთვის, ვისაც სურს ნათლად დაინახოს სურათი და სწრაფად გადადგას შემდეგი ნაბიჯი.",
      startExploring: "დაათვალიერე",
      seeHow: "ნახე, როგორ მუშაობს",
      marketAccess: "წვდომა ბაზარზე",
      spotFee: "სპოტ საკომისიო",
      tradePairs: "სავაჭრო წყვილი",
      portfolioValue: "პორტფელის ღირებულება",
      liveSnapshot: "ბაზრის ცოცხალი სურათი",
      marketOverview: "ბაზრის მიმოხილვა",
      whatsMoving: "ნახე, რა მოძრაობს დღეს.",
      tradeNow: "დაიწყე ვაჭრობა →",
      asset: "აქტივი",
      lastPrice: "ბოლო ფასი",
      change24h: "24 სთ ცვლილება",
      marketCap: "კაპიტალიზაცია",
      trade: "ვაჭრობა",
      builtAroundYou: "შენზე მორგებული",
      everythingTitle: "ყველაფერი, რაც გჭირდება.|არაფერი ზედმეტი.",
      simpleTitle: "მარტივი თავიდანვე",
      simpleText: "ბალანსი, ორდერები და ბაზრის მოძრაობა — ერთ ეკრანზე, ზედმეტი დეტალების გარეშე.",
      yourWayTitle: "ივაჭრე ისე, როგორც გირჩევნია",
      yourWayText:
        "სპოტი, ავტომატური შენაძენები და გაფართოებული ორდერები ერთ სივრცეშია თავმოყრილი.",
      securityTitle: "უსაფრთხოება უპირველესად",
      securityText:
        "მრავალშრიანი დაცვა და გამჭვირვალე პარამეტრები, რომ ანგარიში მხოლოდ შენს კონტროლში იყოს.",
      ready: "როცა მზად იქნები",
      ctaTitle: "შენი შემდეგი ნაბიჯი|სწორედ აქ იწყება.",
      openAccount: "გახსენი ანგარიში",
      footer: "ორიგინალური საბირჟო გვერდის კონცეფცია.",
    },
    auth: {
      welcome: "მოგესალმებით",
      createAccount: "შექმენი ანგარიში",
      loginSubtitle: "შედი და ნახე შენი პორტფელი.",
      signupSubtitle: "ვაჭრობას ერთ წუთში იწყებ.",
      login: "შესვლა",
      signup: "რეგისტრაცია",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "მინიმუმ 6 სიმბოლო",
      submitLogin: "შესვლა →",
      submitSignup: "ანგარიშის შექმნა →",
      startingBalance: "ახალი ანგარიში $0-ით იწყება — ბალანსი კრიპტოს შეტანით შეავსე.",
      genericError: "რაღაც ვერ მოხერხდა",
    },
  },

  en: {
    nav: {
      markets: "Markets",
      whyNovax: "Why GNG",
      security: "Security",
      portfolio: "Portfolio",
      aiTrading: "AI Trading",
      botPlans: "Bot Plans",
      orders: "Orders",
      recurring: "Recurring",
      referrals: "Referrals",
      wallet: "Wallet",
    },
    common: {
      menu: "Menu",
      close: "Close",
      login: "Log in",
      signUp: "Create account",
      signOut: "Sign out",
      dashboard: "Go to dashboard →",
      language: "Language",
      portfolio: "Portfolio",
      email: "Email",
      password: "Password",
      backHome: "← Back to home",
      pleaseWait: "Please wait...",
    },
    landing: {
      heroEyebrow: "The calm way to trade",
      heroTitle: "Move with the market.|Stay in control.",
      heroText:
        "A thoughtful home for digital assets, built for people who want a clear view and a faster next move.",
      startExploring: "Start exploring",
      seeHow: "See how it works",
      marketAccess: "market access",
      spotFee: "spot fee from",
      tradePairs: "trade pairs",
      portfolioValue: "Portfolio value",
      liveSnapshot: "Live market snapshot",
      marketOverview: "Market overview",
      whatsMoving: "See what's moving.",
      tradeNow: "Trade now →",
      asset: "Asset",
      lastPrice: "Last price",
      change24h: "24h change",
      marketCap: "Market cap",
      trade: "Trade",
      builtAroundYou: "Built around you",
      everythingTitle: "Everything you need.|Nothing in your way.",
      simpleTitle: "Simple by design",
      simpleText: "See balances, orders, and market movement at a glance without the clutter.",
      yourWayTitle: "Trade your way",
      yourWayText: "Spot, recurring buys, and advanced orders all live in one focused workspace.",
      securityTitle: "Security first",
      securityText:
        "Layered protection and transparent controls help keep your account in your hands.",
      ready: "Ready when you are",
      ctaTitle: "Your next move|starts here.",
      openAccount: "Open your account",
      footer: "Original exchange landing page concept.",
    },
    auth: {
      welcome: "Welcome back",
      createAccount: "Create your account",
      loginSubtitle: "Sign in to access your portfolio.",
      signupSubtitle: "Start trading in under a minute.",
      login: "Log in",
      signup: "Sign up",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "At least 6 characters",
      submitLogin: "Log in →",
      submitSignup: "Create account →",
      startingBalance: "New accounts start at $0 — fund your balance with a crypto deposit.",
      genericError: "Something went wrong",
    },
  },
};
