import { useEffect, useMemo, useState } from 'react';
import { useLanguage } from '@/lib/language';
const KEY='gng_sandbox_bots', DAY=86400000;
const PLANS=[{id:'free',rate:.01,price:0,name:'Free AI Trader'},{id:'pro',rate:.03,price:150,name:'Pro AI Trader'},{id:'elite',rate:.05,price:250,name:'Elite AI Trader'}];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{balance:1000,unlocked:['free'],active:'free',last:Date.now()}}catch{return {balance:1000,unlocked:['free'],active:'free',last:Date.now()}}}
export default function BotPlans(){
 const {language}=useLanguage(),[state,setState]=useState(load),[notice,setNotice]=useState(''),active=useMemo(()=>PLANS.find(p=>p.id===state.active)||PLANS[0],[state.active]),ka=language==='ka';
 function save(next,message){setState(next);localStorage.setItem(KEY,JSON.stringify(next));setNotice(message)}
 useEffect(()=>{const days=Math.floor((Date.now()-state.last)/DAY);if(!days)return;const profit=Number((state.balance*active.rate*days).toFixed(2));save({...state,balance:state.balance+profit,last:state.last+days*DAY},ka?'დაემატა სიმულირებული მოგება: $'+profit.toFixed(2):'Simulated profit added: $'+profit.toFixed(2))},[]);
 function choose(plan){if(!state.unlocked.includes(plan.id)){if(state.balance<plan.price)return setNotice(ka?'საკმარისი სატესტო კრედიტი არ გაქვს.':'Not enough sandbox credits.');return save({...state,balance:state.balance-plan.price,unlocked:[...state.unlocked,plan.id],active:plan.id},ka?'ბოტი გაიხსნა და გააქტიურდა.':'Bot unlocked and activated.')}save({...state,active:plan.id},ka?'აქტიური ბოტი განახლდა.':'Active bot updated.')}
 return <div className="fade-up" style={{maxWidth:980}}><h1 className="page-title">{ka?'AI ბოტ-გეგმები':'AI Bot Plans'}</h1><p className="page-sub">{ka?'მხოლოდ ტესტირებისთვის — თანხა და მოგება სიმულირებულია.':'For testing only — all balances and returns are simulated.'}</p><div className="card" style={{marginTop:24,marginBottom:24}}><p className="eyebrow">{ka?'სატესტო საფულე':'Sandbox wallet'}</p><div style={{fontSize:30,fontWeight:800}}>{'$'}{state.balance.toFixed(2)}</div><p className="muted-2">{ka?'აქტიური ბოტი: ':'Active bot: '}{active.name} · {(active.rate*100).toFixed(0)}% {ka?'დღეში':'per day'}</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(240px, 1fr))',gap:18}}>{PLANS.map(plan=>{const unlocked=state.unlocked.includes(plan.id),current=plan.id===state.active;return <div className="card" key={plan.id} style={{border:current?'1px solid var(--teal)':undefined}}><h2 style={{fontSize:18}}>{plan.name}</h2><div className="gain" style={{fontSize:28,fontWeight:800,margin:'14px 0'}}>{(plan.rate*100).toFixed(0)}% <small>{ka?'დღეში':'per day'}</small></div><p className="muted-2">{ka?'სიმულირებული ყოველდღიური შედეგი':'Simulated daily return'}</p><p style={{margin:'16px 0',fontWeight:700}}>{plan.price?'$'+plan.price+' '+(ka?'სატესტო კრედიტი':'sandbox credits'):(ka?'უფასო':'Free')}</p><button className={current?'btn ghost':'btn'} style={{width:'100%',justifyContent:'center'}} onClick={()=>choose(plan)} disabled={current}>{current?(ka?'აქტიური':'Active'):unlocked?(ka?'გააქტიურება':'Activate'):(ka?'გახსნა':'Unlock')}</button></div>})}</div>{notice&&<div className="toast success">{notice}</div>}</div>
}